
package com.serv.act;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SsoWS", targetNamespace = "http://act.serv.com", wsdlLocation = "http://192.168.0.117/iamWS/services/SsoWS?wsdl")
public class SsoWS extends Service
{

    private final static URL SSOWS_WSDL_LOCATION;
    private final static WebServiceException SSOWS_EXCEPTION;
    private final static QName SSOWS_QNAME = new QName("http://act.serv.com", "SsoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.117/iamWS/services/SsoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SSOWS_WSDL_LOCATION = url;
        SSOWS_EXCEPTION = e;
    }

    public SsoWS() {
        super(__getWsdlLocation(), SSOWS_QNAME);
    }

    public SsoWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), SSOWS_QNAME);
    }

    public SsoWS(URL wsdlLocation) {
        super(wsdlLocation, SSOWS_QNAME);
    }

    public SsoWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SSOWS_QNAME);
    }

    public SsoWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SsoWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SsoWSPortType
     */
    @WebEndpoint(name = "SsoWSHttpSoap11Endpoint")
    public SsoWSPortType getSsoWSHttpSoap11Endpoint() {
        return super.getPort(new QName("http://act.serv.com", "SsoWSHttpSoap11Endpoint"), SsoWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SsoWSPortType
     */
    @WebEndpoint(name = "SsoWSHttpSoap11Endpoint")
    public SsoWSPortType getSsoWSHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://act.serv.com", "SsoWSHttpSoap11Endpoint"), SsoWSPortType.class);
    }

    private static URL __getWsdlLocation() {
        if (SSOWS_EXCEPTION!= null) {
            throw SSOWS_EXCEPTION;
        }
        return SSOWS_WSDL_LOCATION;
    }

}
